name: Terraform Security

on:
  push:
    branches:
      - main
    paths:
      - "modules/security/**"
      - "accounts/dev-account-alpha/security/**"
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

concurrency:
  group: terraform-security-${{ github.ref }}
  cancel-in-progress: false

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::223374428235:role/github-actions-oidc-role
          aws-region: ap-south-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: accounts/dev-account-alpha/security
        run: terraform init

      - name: Terraform Plan
        working-directory: accounts/dev-account-alpha/security
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        working-directory: accounts/dev-account-alpha/security
        run: terraform apply -auto-approve tfplan
